apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-api-service
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: new-api-service
  template:
    metadata:
      labels:
        app: new-api-service
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: new-api-service
        ports:
        - containerPort: 80
